import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFile,readdir} from 'node:fs/promises';
import worker,{isAdmin,rankChunks,imageMime} from '../worker/index.js';
import {authEnv,tokens,cookie,token} from './auth-fixture.mjs';
async function fixture(){const sqlite=new DatabaseSync(':memory:');for(const f of (await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')))sqlite.exec(await readFile(new URL('../drizzle/'+f,import.meta.url),'utf8'));const blobs=new Map();const env={...authEnv,OPENAI_MODEL:'fixture-model',ASSETS:{async fetch(request){return new URL(request.url).pathname==='/index.html'?new Response('<html>Owner studio</html>',{headers:{'content-type':'text/html'}}):new Response('Not found',{status:404});}},CREDENTIAL_ENCRYPTION_KEY:Buffer.alloc(32,3).toString('base64'),DB:{prepare(sql){return{bind(...args){const query=sqlite.prepare(sql);return {async first(){return query.get(...args)||null;},async all(){return{results:query.all(...args)};},async run(){const r=query.run(...args);return{meta:{changes:Number(r.changes)}};}};}};}},BUCKET:{async put(key,bytes,meta){blobs.set(key,{bytes,meta});},async get(key){const item=blobs.get(key);return item?{arrayBuffer:async()=>item.bytes.buffer.slice(item.bytes.byteOffset,item.bytes.byteOffset+item.bytes.byteLength),body:item.bytes,httpMetadata:item.meta.httpMetadata}:null;},async delete(key){blobs.delete(key);}}};const headers={origin:'https://app.test',...cookie(tokens.owner)};const req=async(path,method='GET',body,auth=true,extra={})=>worker.fetch(new Request('https://app.test'+path,{method,headers:{...(auth?headers:{origin:'https://app.test'}),...extra},...(body===undefined?{}:{body:body instanceof FormData?body:JSON.stringify(body)})}),env);return{env,sqlite,blobs,req,headers};}
const fields={title:'Four buying beliefs',summary:'Build the beliefs people need before buying.',points:['Understand the problem.'],application:['Start with the customer’s current assumption.'],content:'Four buying beliefs: problem, opportunity, self, provider. Start by diagnosing the current assumption before proposing a content angle.',status:'published'};
function form(data=fields){const f=new FormData();f.set('fields',JSON.stringify(data));return f;}
test('owner authorization uses only a verified stable user ID allowlist',()=>{assert.equal(isAdmin(null,authEnv),false);assert.equal(isAdmin({userId:'user_other_id'},authEnv),false);assert.equal(isAdmin({userId:'user_owner'},authEnv),true);assert.equal(isAdmin({userId:'user_owner'},{}),false);});
test('public callers cannot read or mutate admin records; cross-origin writes fail',async()=>{const {req}=await fixture();assert.equal((await req('/api/admin/blueprints','GET',undefined,false)).status,403);assert.equal((await req('/api/admin/blueprints','POST',form(),false)).status,403);assert.equal((await req('/api/admin/blueprints','POST',form(),true,{origin:'https://evil.test'})).status,403);});
test('drafts stay private; publish, revise, and delete use revision checks',async()=>{const {req}=await fixture();const created=await(await req('/api/admin/blueprints','POST',form({...fields,status:'draft'}))).json();const id=created.item.id;assert.equal((await(await req('/api/blueprints','GET',undefined,false)).json()).items.length,0);assert.equal((await req('/api/admin/blueprints/'+id,'PUT',form({...fields,revision:0}))).status,409);assert.equal((await req('/api/admin/blueprints/'+id,'PUT',form({...fields,revision:1}))).status,200);const published=await(await req('/api/blueprints','GET',undefined,false)).json();assert.equal(published.items.length,1);assert.equal('content' in published.items[0],false);assert.equal((await req('/api/admin/blueprints/'+id,'DELETE',{revision:1})).status,409);assert.equal((await req('/api/admin/blueprints/'+id,'DELETE',{revision:2})).status,200);});
test('image bytes are validated and draft assets are not public',async()=>{const {req,blobs}=await fixture();const f=form({...fields,status:'draft'});const png=Uint8Array.from([137,80,78,71,13,10,26,10,0]);f.set('image',new Blob([png],{type:'image/png'}),'framework.png');const r=await req('/api/admin/blueprints','POST',f);assert.equal(r.status,201);const id=(await r.json()).item.id;assert.equal(blobs.size,1);assert.equal((await req('/api/blueprints/'+id+'/image','GET',undefined,false)).status,404);assert.equal((await req('/api/blueprints/'+id+'/image')).status,200);const bad=form();bad.set('image',new Blob(['<svg></svg>'],{type:'image/png'}),'fake.png');assert.equal((await req('/api/admin/blueprints','POST',bad)).status,400);});
test('summary generation returns editable proposals without publishing',async()=>{const {req,env,sqlite}=await fixture();env.OPENAI_API_KEY='test-key';const original=globalThis.fetch;let payload;globalThis.fetch=async(u,o)=>{payload=JSON.parse(o.body);return Response.json({output_text:JSON.stringify({...fields,reviewNotes:[]})});};try{const f=new FormData();f.set('source',new Blob(['%PDF-source'],{type:'application/pdf'}),'framework.pdf');const r=await req('/api/admin/blueprints/analyze','POST',f);assert.equal(r.status,200);assert.equal((await r.json()).summary,fields.summary);assert.equal(payload.input[0].content[0].type,'input_file');assert.equal(sqlite.prepare('SELECT count(*) n FROM blueprints').get().n,0);}finally{globalThis.fetch=original;}});
test('API keys are encrypted and never exposed by session or connection reads',async()=>{const {req,env,sqlite}=await fixture();const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({data:[]});try{const key='sk-private-abcdefghijklmnop';assert.equal((await req('/api/admin/connection','PUT',{key})).status,200);const saved=sqlite.prepare("SELECT value FROM settings WHERE id='openai'").get().value;assert.ok(!saved.includes(key));const publicSession=await(await req('/api/session','GET',undefined,false)).json();assert.deepEqual(publicSession,{admin:false,signedIn:false,userId:null,authConfigured:true,aiConfigured:true,allowance:{limit:100,used:0,remaining:100}});assert.deepEqual(await(await req('/api/admin/connection')).json(),{configured:true,source:'encrypted',managedBySecret:false,storageAvailable:true,model:'fixture-model'});assert.equal('OPENAI_API_KEY' in env,false);}finally{globalThis.fetch=original;}});
test('chat requires sign-in and conversations are private to the account',async()=>{const {req}=await fixture();assert.equal((await req('/api/chats','POST',{},false)).status,401);assert.equal((await req('/api/chats','POST',{},false,{cookie:'bp_visitor='+crypto.randomUUID()})).status,401);const c=await(await req('/api/chats','POST',{},false,cookie(tokens.one))).json();assert.equal((await req('/api/chats/'+c.item.id,'GET',undefined,false)).status,404);assert.equal((await req('/api/chats/'+c.item.id,'GET',undefined,false,cookie(tokens.two))).status,404);assert.equal((await req('/api/chats/'+c.item.id,'GET',undefined,false,cookie(tokens.one))).status,200);});
test('strategist retrieves the original content, cites only supplied sources, and retries idempotently',async()=>{const {req,env}=await fixture();env.OPENAI_API_KEY='test-key';const bp=(await(await req('/api/admin/blueprints','POST',form())).json()).item;const identity=cookie(tokens.one);const c=(await(await req('/api/chats','POST',{blueprintId:bp.id},false,identity)).json()).item;const original=globalThis.fetch;let calls=0;globalThis.fetch=async(u,o)=>{calls++;const payload=JSON.parse(o.body);assert.equal(payload.model,'fixture-model');if(payload.text.format.name==='blueprint_selection')return Response.json({output_text:JSON.stringify({ids:[bp.id,'invented-id']})});const input=JSON.parse(payload.input);assert.ok(input.frameworks[0].excerpts.join('').includes('problem, opportunity, self, provider'));return Response.json({output_text:JSON.stringify({message:'Start with the problem belief. What does your audience currently assume?',sourceIds:[bp.id,'invented-id']})});};try{const turn={message:'How do I apply buying beliefs?',revision:c.revision,requestId:'request-one'};const r=await req('/api/chats/'+c.id+'/turn','POST',turn,false,identity);assert.equal(r.status,200);const d=await r.json();assert.equal(d.item.messages.length,2);assert.equal(d.allowance.remaining,99);assert.deepEqual(d.item.sources,[{id:bp.id,title:bp.title}]);const retry=await req('/api/chats/'+c.id+'/turn','POST',turn,false,identity);assert.equal(retry.status,200);assert.equal(calls,2);}finally{globalThis.fetch=original;}});
test('provider failures preserve the previous conversation and release the lease',async()=>{const {req,env,sqlite}=await fixture();env.OPENAI_API_KEY='test';const identity=cookie(tokens.one);const c=(await(await req('/api/chats','POST',{},false,identity)).json()).item;const original=globalThis.fetch;globalThis.fetch=async()=>new Response('',{status:429});try{const r=await req('/api/chats/'+c.id+'/turn','POST',{message:'Help me',revision:1,requestId:'retry'},false,identity);assert.equal(r.status,429);const row=sqlite.prepare('SELECT * FROM chats WHERE id=?').get(c.id);assert.equal(row.messages,'[]');assert.equal(row.lease,null);assert.equal((await(await req('/api/session','GET',undefined,false,identity)).json()).allowance.remaining,100);}finally{globalThis.fetch=original;}});
test('chunk selection retains matching methodology and image detection rejects active content',()=>{assert.ok(rankChunks('a'.repeat(3500)+'opportunity belief and diagnosis','opportunity diagnosis',1)[0].includes('opportunity'));assert.throws(()=>imageMime(new TextEncoder().encode('<script>alert(1)</script>')));});

test('100 messages are shared across chats and devices; concurrent turns cannot exceed the allowance',async()=>{
 const {req,env,sqlite}=await fixture();env.OPENAI_API_KEY='test';const identity=cookie(tokens.quota);
 const create=async()=> (await(await req('/api/chats','POST',{},false,identity)).json()).item;
 const seed=await create();sqlite.prepare('UPDATE chats SET messages=? WHERE id=?').run(JSON.stringify(Array.from({length:198},(_,i)=>({role:i%2?'assistant':'user',text:'previous'}))),seed.id);
 const a=await create(),b=await create();let release,started;const ready=new Promise(r=>started=r);const original=globalThis.fetch;let calls=0;
 globalThis.fetch=async()=>{calls++;started();await new Promise(r=>release=r);return Response.json({output_text:JSON.stringify({message:'Helpful answer',sourceIds:[]})});};
 try{const pending=req('/api/chats/'+a.id+'/turn','POST',{message:'Help',revision:1,requestId:'last'},false,identity);await ready;
 assert.equal((await req('/api/chats/'+b.id+'/turn','POST',{message:'Help',revision:1,requestId:'parallel'},false,identity)).status,409);
 release();const result=await pending;assert.equal(result.status,200);assert.equal((await result.json()).allowance.remaining,0);
 assert.equal((await req('/api/chats/'+a.id+'/turn','POST',{message:'Help',revision:1,requestId:'last'},false,identity)).status,200);
 assert.equal((await req('/api/chats/'+b.id+'/turn','POST',{message:'Help',revision:1,requestId:'over'},false,identity)).status,429);
 assert.equal(calls,1);assert.equal((await(await req('/api/session','GET',undefined,false,identity)).json()).allowance.remaining,0);
 }finally{globalThis.fetch=original;}
});
test('transcripts work alone and with a saved image, persist privately, and can be cleared',async()=>{const {req,env}=await fixture();env.OPENAI_API_KEY='test';const original=globalThis.fetch;let parts;globalThis.fetch=async(u,o)=>{parts=JSON.parse(o.body).input[0].content;return Response.json({output_text:JSON.stringify({...fields,reviewNotes:[]})});};try{const transcript='My teaching transcript explains the opportunity belief.';const only=new FormData();only.set('transcript',transcript);assert.equal((await req('/api/admin/blueprints/analyze','POST',only)).status,200);assert.ok(parts.some(p=>p.type==='input_text'&&p.text.includes(transcript)));const upload=form({...fields,transcript});upload.set('image',new Blob([Uint8Array.from([137,80,78,71,13,10,26,10,0])],{type:'image/png'}),'cover.png');const created=(await(await req('/api/admin/blueprints','POST',upload)).json()).item;assert.equal(created.transcript,transcript);const both=new FormData();both.set('id',created.id);both.set('transcript',transcript);assert.equal((await req('/api/admin/blueprints/analyze','POST',both)).status,200);assert.ok(parts.some(p=>p.type==='input_image'));assert.ok(parts.some(p=>p.text?.includes(transcript)));const pub=(await(await req('/api/blueprints','GET',undefined,false)).json()).items[0];assert.equal('transcript' in pub,false);const updated=await req('/api/admin/blueprints/'+created.id,'PUT',form({...fields,transcript:'',revision:1}));assert.equal((await updated.json()).item.transcript,'');const oversized=new FormData();oversized.set('transcript','a'.repeat(120001));assert.equal((await req('/api/admin/blueprints/analyze','POST',oversized)).status,400);}finally{globalThis.fetch=original;}});

test('admin page redirects anonymous visitors and rejects other signed-in accounts',async()=>{const {req}=await fixture();const anonymous=await req('/admin','GET',undefined,false);assert.equal(anonymous.status,302);assert.equal(anonymous.headers.get('location'),'https://app.test/sign-in?return_to=%2Fadmin');assert.match(anonymous.headers.get('cache-control'),/no-store/);const other=await req('/admin','GET',undefined,false,cookie(tokens.other));assert.equal(other.status,403);assert.match(other.headers.get('cache-control'),/no-store/);const owner=await req('/admin');assert.equal(owner.status,200);assert.match(owner.headers.get('cache-control'),/no-store/);});
test('all admin actions deny anonymous and non-owner accounts before touching data or AI',async()=>{const {req,sqlite}=await fixture();const id='12345678-abcd-abcd-abcd-123456789abc';const routes=[['/api/admin/blueprints','GET'],['/api/admin/blueprints','POST'],['/api/admin/blueprints/'+id,'PUT'],['/api/admin/blueprints/'+id,'DELETE'],['/api/admin/blueprints/analyze','POST'],['/api/admin/connection','GET'],['/api/admin/connection','PUT']];for(const identity of [{},cookie(tokens.other),{'oai-authenticated-user-email':'owner@example.com'}]){for(const [path,method] of routes){const r=await req(path,method,method==='GET'?undefined:{},false,identity);assert.equal(r.status,403,path+' '+method);}}assert.equal(sqlite.prepare('SELECT count(*) n FROM blueprints').get().n,0);assert.equal(sqlite.prepare('SELECT count(*) n FROM settings').get().n,0);});

test('Sites identity headers cannot sign in or elevate another Clerk account',async()=>{const {req}=await fixture();const spoof={'oai-authenticated-user-id':'owner-id','oai-authenticated-user-email':'owner@example.com'};assert.equal((await req('/api/chats','POST',{},false,spoof)).status,401);assert.equal((await req('/api/admin/blueprints','GET',undefined,false,spoof)).status,403);assert.equal((await req('/api/admin/blueprints','GET',undefined,false,{...cookie(tokens.other),...spoof})).status,403);const session=await(await req('/api/session','GET',undefined,false,spoof)).json();assert.equal(session.signedIn,false);assert.equal(session.admin,false);});
test('an invalid Clerk JWT fails closed before accessing private conversation data',async()=>{const {req}=await fixture();const bad=await token('user_owner',{exp:Math.floor(Date.now()/1000)-120});assert.equal((await req('/api/admin/blueprints','GET',undefined,false,cookie(bad))).status,403);assert.equal((await req('/api/chats','POST',{},false,cookie(bad))).status,401);});
test('authentication configuration exposes public names only and supports sign-in pages',async()=>{const {req}=await fixture();const config=await(await req('/api/auth/config','GET',undefined,false)).json();assert.equal(config.configured,true);assert.match(config.publishableKey,/^pk_test_/);assert.equal('CLERK_JWT_KEY' in config,false);assert.equal((await req('/sign-in','GET',undefined,false)).status,200);assert.equal((await req('/sign-up','GET',undefined,false)).status,200);const head=await req('/sign-in','HEAD',undefined,false);assert.equal(head.status,200);assert.equal(await head.text(),'');assert.match(head.headers.get('content-security-policy'),/clerk\.app\.test/);});
test('server-side OpenAI secret takes precedence and encrypted key updates fail clearly',async()=>{const {req,env,sqlite}=await fixture();env.OPENAI_API_KEY='server-private-key';const config=await(await req('/api/admin/connection')).json();assert.equal(config.source,'environment');assert.equal(config.managedBySecret,true);assert.equal(JSON.stringify(config).includes(env.OPENAI_API_KEY),false);assert.equal((await req('/api/admin/connection','PUT',{key:'sk-new-key-abcdefghijklmnop'})).status,409);assert.equal(sqlite.prepare('SELECT count(*) n FROM settings').get().n,0);});
test('voice transcription is signed-in, allowance-gated, and forwards only server credentials',async()=>{const {req,env}=await fixture();env.OPENAI_API_KEY='server-private-key';env.OPENAI_TRANSCRIPTION_MODEL='fixture-transcribe';const audio=new FormData();audio.set('audio',new Blob(['audio'],{type:'audio/webm'}),'audio.webm');assert.equal((await req('/api/transcribe','POST',audio,false)).status,401);const original=globalThis.fetch;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/audio/transcriptions');assert.equal(options.headers.authorization,'Bearer '+env.OPENAI_API_KEY);assert.equal(options.body.get('model'),'fixture-transcribe');return Response.json({text:'My business question'});};try{const r=await req('/api/transcribe','POST',audio,false,cookie(tokens.one));assert.equal(r.status,200);assert.deepEqual(await r.json(),{text:'My business question'});const session=await(await req('/api/session','GET',undefined,false,cookie(tokens.one))).json();assert.equal(session.allowance.remaining,100);}finally{globalThis.fetch=original;}});
