// Adapted from ContentOS web/voice.js: the same MediaRecorder → reviewable transcript flow.
(()=>{let recorder=null,stream=null,chunks=[],blob=null,busy=false,starting=false,timer=null,started=0,field=null,panel=null,bytes=0,download=null;
 const $=id=>document.getElementById(id);const active=()=>!!recorder||busy||starting||!!blob;
 function stopTracks(){stream?.getTracks().forEach(t=>t.stop());stream=null;}
 function controls(text){if(!panel)return;$('voiceStatus').textContent=text;$('voicePause').hidden=!recorder;$('voiceFinish').hidden=!recorder;$('voiceRetry').hidden=!blob||!!recorder||busy;$('voiceCancel').disabled=busy||starting;$('voicePause').disabled=starting;$('voiceFinish').disabled=starting;$('sgMessage').readOnly=!!recorder||busy||starting;$('sgSend').disabled=!!recorder||busy||starting;$('sgVoice').disabled=active();document.dispatchEvent(new CustomEvent('blueprint-voice-state'));}
 function mount(host){if(panel)panel.remove();panel=document.createElement('section');panel.className='voice-controls';panel.id='voiceDialog';panel.innerHTML='<p id="voiceStatus" role="status">Preparing microphone…</p><div><button id="voicePause" type="button" class="idea-action">Pause</button><button id="voiceFinish" type="button" class="copy-button">Finish recording</button><button id="voiceRetry" type="button" class="copy-button" hidden>Retry transcription</button><button id="voiceCancel" type="button" class="idea-action">Discard recording</button><a id="voiceDownload" download="voice-message.webm" hidden>Save audio</a></div>';$('sgReply').before(panel);$('voicePause').onclick=()=>{if(recorder?.state==='recording'){recorder.pause();$('voicePause').textContent='Resume';controls('Recording paused.');}else if(recorder?.state==='paused'){recorder.resume();$('voicePause').textContent='Pause';controls('Recording…');}};$('voiceFinish').onclick=finish;$('voiceRetry').onclick=transcribe;$('voiceCancel').onclick=clear;}
 async function record(mode,host,target){if(active())return;field=target;mount(host);starting=true;controls('Preparing microphone…');let requested;try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('This browser cannot record audio. You can still type your message.');let expired=false,permissionTimer;const permission=navigator.mediaDevices.getUserMedia({audio:true});permission.then(s=>{if(expired)s.getTracks().forEach(t=>t.stop());},()=>{});try{requested=await Promise.race([permission,new Promise((_,reject)=>{permissionTimer=setTimeout(()=>{expired=true;reject(Error('The microphone did not respond. Check browser permission and try again.'));},20000);})]);}finally{clearTimeout(permissionTimer);}stream=requested;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunks=[];bytes=0;recorder.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);bytes+=e.data.size;if(bytes>5.5*1024*1024)finish();}};recorder.onerror=()=>{finish();controls('Recording interrupted. Finishing the audio collected so far…');};recorder.onstop=()=>{const type=recorder?.mimeType||mime||'audio/webm';blob=new Blob(chunks,{type});recorder=null;stopTracks();clearInterval(timer);if(blob.size){download=URL.createObjectURL(blob);$('voiceDownload').href=download;$('voiceDownload').hidden=false;void transcribe();}else{blob=null;controls('No audio captured. Discard and try again.');}};recorder.start(1000);started=Date.now();timer=setInterval(()=>{if(!recorder)return;const seconds=Math.floor((Date.now()-started)/1000);if(seconds>=180){finish();return;}if(recorder.state==='recording')$('voiceStatus').textContent='Recording · '+Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');},1000);starting=false;controls('Recording…');}catch(e){starting=false;recorder=null;stopTracks();controls(e.message||'Microphone permission was denied. You can still type.');}}
 function finish(){if(recorder&&recorder.state!=='inactive'){controls('Finishing recording…');recorder.stop();}}
 async function transcribe(){if(!blob||busy)return;busy=true;controls('Transcribing your message…');try{const form=new FormData();form.append('audio',blob,'message.'+(blob.type.includes('mp4')?'mp4':'webm'));const token=await window.BlueprintAuth?.getToken();const r=await fetch('/api/transcribe',{method:'POST',body:form,headers:token?{authorization:'Bearer '+token}:{},signal:AbortSignal.timeout(130000)}),d=await r.json();if(!r.ok)throw Error(d.error||'Transcription could not finish.');const input=$(field);const text=(input.value.trim()+' '+d.text).trim();if(text.length>6000)throw Error('This transcript exceeds the message limit. Save your audio and send a shorter recording.');input.value=text;input.dispatchEvent(new Event('input'));blob=null;busy=false;panel.remove();panel=null;URL.revokeObjectURL(download);download=null;$('sgMessage').readOnly=false;document.dispatchEvent(new CustomEvent('blueprint-voice-state'));input.focus();}catch(e){busy=false;controls(e.message||'Transcription was interrupted. Your audio is here for retry.');}}
 function clear(){if(busy||starting)return;if(recorder){recorder.onstop=null;recorder.stop();recorder=null;}stopTracks();clearInterval(timer);chunks=[];blob=null;URL.revokeObjectURL(download);download=null;panel?.remove();panel=null;if($('sgMessage'))$('sgMessage').readOnly=false;document.dispatchEvent(new CustomEvent('blueprint-voice-state'));}
 window.Voice={record,isActive:active,clear,refreshControls:()=>{}};window.addEventListener('beforeunload',e=>{if(active()){e.preventDefault();e.returnValue='';}});
})();
